---
title: "A Bootcamp for Reproducible Data Analysis using R"
author: "Robin Jeffries"
date: "\ `r Sys.Date()`"
output:
  ioslides_presentation:
  beamer_presentation: default
---

# Introduction to the class

## Goals 

- Target audience: Anyone who wants to do their own data analysis!

- Primer to get the complete novice up and running with the basic knowledge of how to use the statistical programming language R. 
- Topics include: R programming basics, importing data, properties of tidy data, visualizing data, reproducible research with Markdown and basic data management and debugging. 

- Get you up and running with basic knowledge of `R` ASAP.
- Math 315 uses R heavily. This course is designed as a co- or pre-requisite. 


## Why use R? 
- Free!
- Cross platform. 
- Tons of free tutorials. 
- The [R-project](http://www.r-project.org/) is a free open-source programming language that can easily create dynamic graphics for data visualization. 
- It is also a flexible statistical analysis toolkit, and provides access to powerful cutting edge analytics. 
- The fastest growing statistical analysis program in the Natural Sciences according to the Journal [Nature](http://www.nature.com/news/programming-tools-adventures-with-r-1.16609).
- The R community is a robust, vibrant community of users that has [grown rapidly](http://blog.revolutionanalytics.com/2015/05/r-tops-2015-kdnuggets-software-poll-.html) in the past few years. 
- As has the number of [companies](http://www.revolutionanalytics.com/companies-using-r) who rely on R as their data science platform. 


##  Why use R Studio
- Also free!
- Customizable workspace that docks all windows together. 
- Syntax highlighting, warning errors when missing a closing parentheses. 
- Cross-platform interface. Also works on Windows/iOS/Linux
- Tab completion for functions. Forget the syntax or a variable name? Popup helpers are available. 
- Free training videos available from the developers directly.
- One button publishing of reproducible documents such as reports, interactive visualizations, presentations (like this one!)


## Other ways to learn R
There are literally hundreds of free tutorials on how to learn R. 

These lists were created in 2012 but likely still relevant. 

- [General guides](http://pairach.com/2012/06/17/r_tutorials_non-uni/)  
- [102 University based tutorials](http://pairach.com/2012/02/26/r-tutorials-from-universities-around-the-world/)
 
A couple interactive tutorials. 

- [Data Camp](https://www.datacamp.com/)
- [Try R](http://tryr.codeschool.com/)

And some [YouTube videos](https://www.youtube.com/channel/UCaNIxVagLhqupvUiDK01Mgg).

## Structure of this class
* Content is fully online
* Semi structured. Self-paced but with quiz deadlines. 
* Weekly R problem solving session (Time/Loc TBD)
* Labs - 3 per week.
* Interactive coding sessions to learn R in R using the [Swirl](http://swirlstats.com/) package.
* One quiz per lab. All due by the following Sunday at midnight. 


## Time Committment
* Fast paced 1 unit course conducted over 3 weeks. 
* Learning a programming language is not trivial.
* Expect to spend 10-12 hours per week for these three weeks if you have never programmed before. 

## Getting Help
* Use the forum and problem solving sessions.
* Your first resource is each other. 
* I will **not** answer emails that are in essence "_My code won't run_". Check the forum for a solution first. 
* Prepare a **minimal working example** of your problem on the forum, it may be helpful to include a screenshot of the problem. 


## You will be responsible for

1. Working through each lab fully. 
2. Completing each Swirl lesson. 
3. Completing quizzes for each lab. 
4. Staying on track. 
5. Using the class forum and attending the problem solving sessions to get help.

## Grading

* Credit / No Credit. 
* Achieving 70\% or higher of available points is needed to earn credit. 


## Getting started!
* Once you enroll in Math 199 check the course Blackboard Learn site. Use the link provided there to enroll in the [Piazza](https://piazza.com/account/login) class forum.
* Introduce yourself the class forum board. 
* Download Lab1 and get started coding! 

