---
output:
  pdf_document:
    highlight: pygments
  html_document:
    keep_md: yes
---

# Syllabus for Math 199 - Fall 2015 
## A Bootcamp for Reproducible Data Analysis in R


### Course Description
This bootcamp course serves as a primer to get the complete novice up and running with the basic knowledge of how to use the statistical programming language R. Topics include: R programming basics, importing data, properties of tidy data, visualizing data, reproducible research with Markdown and basic data management and debugging. 

### Course Information
**INSTRUCTOR:** Dr. Robin Jeffries  
**OFFICE:** Holt 216  
**PHONE:** 898-5767  
**E-mail:** rjeffries@csuchico.edu  

### Meeting Times and Locations 
None!
Fully online with in person problem solving sessions each Friday (time and loc TBD). There will be a moderated [Piazza](https://piazza.com/account/login) forum available for discussions and mid-week / late-night help. Check the Blackboard learn course site for the link to enroll in our specific Piazza course forum. 

### Office Hours 
Friday problem solving sessions (time TBD), and by appointment. 

### Time Commitment
This is a fast paced 1 unit course conducted over 3 weeks. Learning a programming language is not trivial, expect to spend 10-12 hours per week for these three weeks if you have never programmed before. 

### Prerequisite
Basic computer literacy. ELM status. 
Review the [Intro to the class]("/lecture_notes/0_1_-_Intro_to_the_class.pdf") slides on instructions on how to install the required programs. 

### Materials

* Textbook: None Required. A list of recommended learning tools will be provided.
* Computer: Mandatory. A reliable computer (laptop preferred) that you can install programs onto. See me if you do not have a personal computer. 
* Reliable internet connection.

### Grading
Credit / No Credit. Achieving 70% or higher of available points is needed to earn credit. Points will be gained by completing each lab, swirl lesson and quiz.  
  
### Adding and Dropping the course
TBD

### Accomodations
If you need course adaptations or accommodations because of a disability or chronic illness, please contact Accessibility Resource Center (ARC) as they are the designated department responsible for approving and coordinating reasonable accommodations and services for students with disabilities. The ARC phone number is 530-898-5959, arcdept@csuchico.edu

### Course outline
The course schedule can be found [here]("Schedule.pdf"). Subject to minor modifications. All content will be made available on Day 1 of the course, however the quizzes and homeworks will have set deadlines. 

It is your responsibility to frequently check the course Piazza forum for updates and changes. 



