---
title: 'Lab 2: Logicial expressions and missing data'
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: cerulean
---

# Introduction 
The goal of this lab is to introduce you to how R evaluates logical expressions and how it handles missing values in data. You will be completing two Swirl lessons. Each lesson will take anywhere from 10-30 minutes and you can stop and restart them at any time. You can type `bye()` to exit and save your progress, just be sure to use the same name each time. At the end of the lesson you will have the option to send me an email letting me know you have completed the lesson. **Do this so I can give you credit!**


## Logic

Complete the **Logic** Swirl lesson. 

### Practice

1. Evaluate ``((111 >= 111) | TRUE) & ((4 + 1) != 5)``
2. Evaluate `!(3+5)`. What does the `!` operator do? How is it different from `!=`? 

### Assessment
Complete the **Logic** quiz on BBLearn.

## Missing Data

Complete the **Missing Values** swirl lesson. 

### Practice

1. When you loaded the missing data swirl lesson, a vector called `Nile` should have been created in your environment. How many missing values does this vector have?
2. Wrap the `sum()` function around the `is.na()` function to find the answer to the above question in one step. Hint: functions can be nested: `f(g(x))`.

### Assessment
Complete the **Missing Data** quiz on BBLearn.

