---
title: 'Lab 3: Subsetting Vectors'
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: cerulean
---

# Introduction 
The goal of this lab is to introduce you to how to extract certain elements from a data vector in R. You will complete one Swirl lessons and some additional exercises specified in this lab. You can stop and restart the `swirl()` lesson at any time, just type `bye()` to save your progress before exiting. Be sure to use the same name each time so you pick up where you left off. At the end of the lesson you will have the option to send me an email letting me know you have completed the lesson. **Do this so I can give you credit!**


## Subsetting vectors using positional indicators and the bracket `[]` notation. 

Complete the **Subsetting Vectors** Swirl lesson. 

### Practice

1. Create a vector of 100 random normal values by typing `rnorm(100)` and assigning it to a vector. 
2. Print out the top 10 values.
3. Print out the values that are greater than 3. Assign this to a new vector object named `y`. 

## Subsetting vectors using `subset()`. 

As you start to learn `R` you will quickly realize that there are multiple ways to write code
that achieves the desired result. In general it comes down to experience, preference, and style.
In this lab we will cover another way to subset the data using the function `subset()`.

1. Read the help file for subset by typing `?subset`. Don't worry if it seems cryptic

### Practice

1. Repeat number 3 from the prior practice but use the `subset()` function. Assign this to a new vector object named `z`.
2. Prove that these two methods produce the exact same subset by typing `identical(y,z)`.


### Assessment
Complete the **Subsetting Vectors** quiz on BBLearn.
<!-- What is head(x) equal to?  x[1:6] -->
<!-- What is the equivelant notation to subset(x[x>0])? x[x>0 & !is.na(x)] -->
<!-- What does subset() do? Return subsets of vectors, matrices or data frames which meet conditions. -->
